### ISSUE TITLE
As a database dev, I'd like to have a reusable workflow for my SQL checks from Bytebase 

### ISSUE THREAD

**Issue by Francois-Werbrouck** [ai-cfia/github-workflows#113]
I'd like to have a reusable workflow for my SQL checks from Bytebase 

- [x] yml reusable workflow
- [x] doc about how to manage the secrets to bind the Bytebase DB and the github repo

**Comment by rngadam** [comment]
@SonOfLope 

all tasks are marked as done; should this be closed (and remaining work in follow up issues) or does the task list need to be updated?

**Comment by SonOfLope** [comment]
Référence branch hasn't been merged with the workflow implemented

**Comment by SonOfLope** [comment]
> Referenced branch hasn't been merged with the workflow implemented



> @SonOfLope
> 
> all tasks are marked as done; should this be closed (and remaining work in follow up issues) or does the task list need to be updated?

Referenced branch hasn't been merged with the workflow implemented

**Comment by SonOfLope** [comment]
Information  available in right pane : 
![image](https://github.com/ai-cfia/github-workflows/assets/73133692/d31f870d-f695-485e-9eb2-bd88bf0dca71)
