### ISSUE TITLE
Create a reusable workflow for github-pages deployment

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#12]
Create a workflow to deploy, will need variable for :
- publish branch
- publish dir
- working dir

Two products are using gh-pages for deployment one using yarn the other npm so will need to find a solution to combine both

**Comment by rngadam** [comment]
missing details about the discussion we've had concerning the differences between the Docusaurus workflow and the React frontend project workflows (npm and yarn) and what alternatives we can consider to unify both.

**Comment by redat97** [comment]
https://github.com/ai-cfia/github-workflows/issues/12#issuecomment-1761910517
i understood put both and then combine but ok will change
