### ISSUE TITLE
Create workflow to update documentation based on change

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/github-workflows#19]
Plan so far is:
- use a workflow to get the diff from new commit
- feed that diff to Azure OpenAI with the documentation for it to have more context
- remove old file and create a new file with the same name which will append the response
- create a new PR with the original commiter as reviewer

**Comment by SonOfLope** [comment]
The proposed workflow relies heavily on an automated system to interpret diffs and generate documentation accordingly. This process introduces a high level of complexity and potential points of failure. Automated systems like Azure OpenAI, might not always interpret changes correctly or generate accurate, relevant documentation. The risk of introducing errors or irrelevant information is significant, which could lead to more harm than good in our documentation. 

Given these concerns, this issue will be closed.
