### ISSUE TITLE
Rename python lint-test job name

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#27]
When choosing a source for status check, the naming convention goes as follow :
"<calling workflow job name> / <reusable workflow job name>". 

![Screenshot_177](https://github.com/ai-cfia/github-workflows/assets/9827730/672f7997-8fbc-4970-8f7b-1dc1b1395bde)

Taking the [fast-api repository](https://github.com/ai-cfia/fastapi-example) as an example, inside the main [workflow](https://github.com/ai-cfia/fastapi-example/blob/main/.github/workflows/gcp-deployment.yml) the first job is called lint-test. This test calls the python test [workflow](https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-lint-test-python.yml) which is called "build". 

By changing the name from build to "lint-test", which would be consistent with the way it's called for the lint-testing of node projects. The purpose of this is so that regardless of the project's language, we can run a script that will require "lint-test / lint-test" to pass and it would be viable for both projects even though they aren't coded in the same language and would allow us to have a standardisation for both project types.

Here is an example of how it currently looks for a repository calling the `.github/workflows/workflow-lint-test-node.yml` file
![Screenshot_178](https://github.com/ai-cfia/github-workflows/assets/9827730/dda18f94-67fc-42b6-8ac4-ce9dfa5018ee)

**Comment by rngadam** [comment]
I'm suspicious that a good naming convention would repeat the same words twice.

**Comment by redat97** [comment]
> I'm suspicious that a good naming convention would repeat the same words twice.

I think the two options is either that or not naming the step in the calling or reusable workflow

**Comment by rngadam** [comment]
@redat97 remind me to discuss this at the next 1:1
