### ISSUE TITLE
Add code-coverage workflow for python

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/github-workflows#4]

**Comment by ThomasCardin** [comment]
Add code coverage for python application

**Comment by rngadam** [comment]
If I click through the commit references here:

![image](https://github.com/ai-cfia/github-workflows/assets/538542/ce11fb94-8bdf-4d84-9305-c1a81da35487)

so looks like a fork that was "privatized"?

**Comment by ThomasCardin** [comment]
See https://github.com/ai-cfia/github-workflows/pull/5
