### ISSUE TITLE
Fix link testing workflow for linkedin

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#44]
Linkedin doesn't allow http request from bots and returns a status code of 999, either we need to exclude linkedin links or mark status code 999 as valid links (both case wouldn't test link just not make the whole workflow fail)

**Comment by rngadam** [comment]
999 should be considered valid; it's an HTTP code returned by a webserver, so likely the link has content valid just not content accessible by the bot.

https://http.dev/999
