### ISSUE TITLE
Create workflow to validate line 80 wrap for all sources

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#45]
Need to create a workflow to make sure all types of files are wrapped at line 80 and doesn't exceed this limit

**Comment by redat97** [comment]
https://github.com/ai-cfia/github-workflows/pull/47
done here

**Comment by rngadam** [comment]
@ThomasCardin this workflow should be running against all markdown which is why i'm surprised you had a markdown with line not wrapped properly.

**Comment by ThomasCardin** [comment]
> @ThomasCardin this workflow should be running against all markdown which is why i'm surprised you had a markdown with line not wrapped properly.

Yes, I just found out that one action inside the workflow is failing because the action is deprecated. I will add this problem to the backlog.
![image](https://github.com/ai-cfia/github-workflows/assets/49320132/486b2403-23fd-4d85-9068-beecaebdca88)

**Comment by ThomasCardin** [comment]
It's working fine. My mistake. I will close this issue
