### ISSUE TITLE
Create a github action to get/push the .tfstate file using Terraform Cloud

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/github-workflows#46]
This workflow will:
- terraform fmt
- terraform int
- terraform validate -no-color
- terraform plan -no-color
- terraform apply -auto-approve

**Comment by rngadam** [comment]
@ThomasCardin Projects field need to be set to organization-wide projects, in this case to DevSecOps:

https://github.com/orgs/ai-cfia/projects/7

tasks ened to be prioritized top to bottom there.

**Comment by ThomasCardin** [comment]
Won't do. This is  my mistake. Everything can be done with the ```backend{}``` tag inside the terraform provider.
