### ISSUE TITLE
Lint YAML files

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/github-workflows#48]
Any source file is subject to linting, including here YAML file.

example output running yamllint against this repo: https://gist.github.com/rngadam/96a1c5f0f7c8489ff5dab0d269b201dc

* create reusable workflow to validate YAML
* document VSC configuration/extension to allow developer to validate YAML files in their IDE

**Comment by SonOfLope** [comment]
@rngadam may I suggest we make use of a [pre-commit hook](https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit) to prevent pushing code violating yaml linting ?

**Comment by rngadam** [comment]
> @rngadam have we considered making use of [pre-commit hooks](https://pre-commit.com/) to point out code issues before allowing a developer to make a commit ?
> example for yaml pre-commit hook [here](https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit)

sure, but that would be in addition to and not in lieu of Github Workflows.

Also, it is more developer-friendly to have them configure linters in their IDE (Github Codespaces) for real-time feedback than quality feedback just before they push the changes so I would invest efforts there.

**Comment by SonOfLope** [comment]
> > @rngadam have we considered making use of [pre-commit hooks](https://pre-commit.com/) to point out code issues before allowing a developer to make a commit ?
> > example for yaml pre-commit hook [here](https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit)
> 
> sure, but that would be in addition to and not in lieu of Github Workflows.

Yes. A PR for a Github workflows is already waiting for review.

> Also, it is more developer-friendly to have them configure linters in their IDE (Github Codespaces) for real-time feedback than quality feedback just before they push the changes so I would invest efforts there.

An extension for that purpose was recommended in the PR added documentation that implements this functionality.
