### ISSUE TITLE
Update vercel deployment to specify node and npm version

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#53]
Currently facing an issue where when trying to deploy to vercel we get an error message saying

npm ERR! notsup Required: {"npm":"^9.8.1","node":"^18.[16](https://github.com/ai-cfia/finesse-frontend/actions/runs/7142585744/job/19452590732#step:6:17).0"}
npm ERR! notsup Actual:   {"npm":"10.2.3","node":"v18.19.0"}

to fix this, we will use the "actions/setup-node@v3" and run "npm install -g npm@9.8.1" to specify a npm and node version

showcase and explain in this PR as well:
https://github.com/ai-cfia/finesse-frontend/pull/49

**Comment by rngadam** [comment]
> to fix this, we will use the "actions/setup-node@v3" and run "npm install -g npm@9.8.1" to specify a npm and node version

you must mean ```"npm install -g npm@11``` because 9.8.1 would not fulfill the version range required?
