### ISSUE TITLE
Azure build and push secret name is misnamed

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#57]
Azure build and push workflow uses a secret called ACR_REGISTRY_NAME but should be ACR_REGISTRY_URL.
The secret is currently not representative of the data it should contain, should provide the whole link not just the name for the login

**Comment by rngadam** [comment]
By link, do you mean URL? what is the format? Not sure LINK makes it clearer. If it's a URL ACR_REGISTRY_URL

**Comment by redat97** [comment]
ah ok yeah

**Comment by ThomasCardin** [comment]
Wont' do
