### ISSUE TITLE
Vercel deployment workflow only comments the URL of the most recent build

### ISSUE THREAD

**Issue by redat97** [ai-cfia/github-workflows#60]
There was a problem where a user couldn't see the changes from the first Pull Request (PR) because the URL only pointed to the most recent build. This is an issue in our CI/CD setup where multiple PRs might be in progress, and the deployment URLs get overwritten or aren't specific to each PR

This will be fixed by adding a preview URL to the GitHub comment and edit the comment for each build with the new preview URL

**Comment by ThomasCardin** [comment]
Won't do. We will preview deployment when this issue (https://github.com/ai-cfia/infra/issues/20) will be solved (iteration 3). No more maintenance time will be put into Vercel
