### ISSUE TITLE
As a DevOps, I would like to know how my developer uses Github

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/github-workflows#67]
- Check how they create PRs and manage them.
- Check how they create issues.
- Check how they develop (are they using Codespaces or developing locally?).
- Check how they monitor systems.
- Check how they check their deployment status.

This issue is created inside this repository because we might need to create a new workflow or GitHub policies.

**Comment by rngadam** [comment]
also debugging, researching dependencies, monitoring their build. should get a diagram of the development workflow and walkthrough that.

**Comment by SonOfLope** [comment]
Done. We created a Devex survey that will be iterated over monthly to address priorities for our developers and how to improve their workflow.

**Comment by rngadam** [comment]
@SonOfLope don't think the survey really covered understanding the developer workflow. we should discuss in-person.
