### ISSUE TITLE
As a DevOps, I would like to fix the markdown lint workflow

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/github-workflows#76]
- The markdown lint workflow still have a problem...

**Comment by rngadam** [comment]
It's a bit strange as a user story ("fix") and the description does not explain what the problem is. In addition, the Projects field is not set.

**Comment by rngadam** [comment]
> It's a bit strange as a user story ("fix") and the description does not explain what the problem is. In addition, the Projects field is not set.

@ThomasCardin
